### ISSUE TITLE
change bin expiration to be based on time since last access

### ISSUE THREAD

**Issue by jyaganeh** [geobin-io/geobin.io#101]
Currently there's a hard expiration on bins, which is less than ideal if you spend time setting up a bin and want to keep using it. We should change bin expiration to keep bins around until they are unused for some amount of time.

This could potentially be worked on leading up to or as a follow on for #82

**Comment by aaronpk** [comment]
Agreed that the data should not persist more than 48 hours even if the bin lasts longer. I think this issue can be safely closed since ryan's PR re-creates the bin if new data is posted to it so bins will always look like they exist.
