### ISSUE TITLE
expose yourselves

### ISSUE THREAD

**Issue by ngoldman** [geobin-io/geobin.io#124]
![screen shot 2015-04-04 at 1 16 01 pm](https://cloud.githubusercontent.com/assets/427322/6994392/d286104a-dacc-11e4-9bd2-4420e3b214a7.png)
![screen shot 2015-04-04 at 1 16 54 pm](https://cloud.githubusercontent.com/assets/427322/6994394/ea1eed08-dacc-11e4-998e-54cf9f56df1d.png)

@jyaganeh @courtf @aranasaurus it's lonely out there :crying_cat_face:

**Comment by aranasaurus** [comment]
🙈

**Comment by jyaganeh** [comment]
* [x] exposed

**Comment by courtf** [comment]
it is done

**Comment by ngoldman** [comment]
![](http://33.media.tumblr.com/tumblr_lpwtgvjbYm1qko4x4o1_500.gif)
