### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by ungoldman** [geobin-io/geobin.io#131]
https://geobin.io is no longer serving the site :(

Wanted to show a good mapping interface to a colleague as an example. Sad to see it appears to be dead.

**Comment by aaronpk** [comment]
well that's weird, I'm not sure why the service stopped. I just started it back up again. I even had it set up as an ubuntu init task.

**Comment by ungoldman** [comment]
looks like it's forcing https which is breaking some third party stuff that was `http` - https://geobin.io/vupkM6pjSr

This pupper is in bad need of a little maintenance
